project:
  type: book
  preview:
    port: 4200

resources:
  - CNAME
  
reference-location: margin # footnotes in margin
link-citations: true       # citations link to references

bibliography: references.bib
reference-section-title: References

crossref:
  fig-prefix: figure
  tbl-prefix: table
  sec-prefix: section

language:
  crossref-ch-prefix: chapter
  crossref-apx-prefix: appendix

df-print: kable
filters:
  - boxes

format:
  html:
    theme:
      light: [flatly, resources/scss/global.scss]
      dark: [darkly, resources/scss/global.scss]
    published-title: "Updated"

  pdf:
    documentclass: scrreprt
    keep-tex: true
    include-in-header: resources/tex/preamble.tex
    citeproc: false # don't run pandoc default citation handling
    csl: chicago-author-date-no-em-dash.csl
    filters:
      - section-bibliographies
    toc-depth: 1 # level 1 headings (i.e. parts and chapters)
    toc-title: Contents # title of table of contents
    links-as-notes: true # turn URLs into sidenotes
    citecolor: DarkGreen # tufte color
    linkcolor: DarkBlue # tufte color
    urlcolor: DarkGreen # tufte color

knitr:
  opts_chunk:
    comment: "#>"
    collapse: TRUE
    cache.lazy: FALSE
    dev: "png"
    dpi: 300

execute: 
  echo: false
  message: false
  warning: false
  error: false
  cache: true
  code-overflow: wrap
  tidy: true

book:
  title: "Machine Learning from Human Preferences"
  subtitle: ""
  author:
    - name: Sang T. Truong
      orcid: 0000-0001-8069-9410
    - name: Sanmi Koyejo
      orcid: 0000-0002-4023-419X
  date: last-modified
  # doi: 10.25936/3jp6-5m50
  repo-url: https://github.com/sangttruong/mlhp
  repo-actions: [source, issue]
  downloads: [pdf]
  sidebar:
    style: "docked"
    footer: license.qmd
  # google-analytics:
  # cookie-consent: true
  chapters:
    - index.qmd
    - 001-introduction.qmd
    - 002-reward_model.qmd
    - 003-measure.qmd
    - 004-optim.qmd
    - 005-align.qmd
